language: node_js
node_js:
  - "stable"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $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
  local_dir: build
  on:
    branch: master

